### ISSUE TITLE
Hello, Question for Testing Dataset in DSTC 11

### ISSUE THREAD

**Issue by haesungpyun** [amazon-science/dstc11-track2-intent-induction#1]
In Test Dataset, it contains only utterances labeled with Inform Intent.
We wonder whether the input in evaluation is the same as the dev dataset in GitHub.

{"intent_id":  "intent_1", "utterances": ["I want to book a flight", "I need a flight", ...]}
{"intent_id":  "intent_2", "utterances": ["I want to reserve a room", "I need a hotel room", ...]}
...

Thank you.

**Comment by jgung** [comment]
Hi @haesungpyun, thank you for your question! During the evaluation phase, dialogues like those in `development/dialogues.jsonl` will be provided, but for different domains (e.g. `test-domain-1/dialogues.jsonl` and `test-domain-2/dialogues.jsonl`).

The utterances in `test-utterances.jsonl` are intended to provide an example of utterances that will be used for evaluation of [Task 2 - Open Intent Induction](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task2-open-intent-induction.md). In this task, evaluation will proceed by training a classifier on the induced intent schema (in the format you mentioned above) and comparing the predicted (induced) intent labels with reference schema intent labels. Please let me know if this answers your question (and see the task description linked above for more details).
