### ISSUE TITLE
When will the test set be sent?

### ISSUE THREAD

**Issue by Chucy2020** [amazon-science/dstc11-track2-intent-induction#10]
hello, excuse me, when will the test set be released? and  how will the test set be distributed? and how do i know if I've signed up successfully?

thanks

**Comment by ODDHOOD** [comment]
I also want to ask, would you like to form a team with me? If you have any questions, you can communicate together. The email is on my homepage, thank you.

**Comment by jgung** [comment]
Thanks for your questions, @Chucy2020!

> when will the test set be released?

We are currently planning to release the test conversations next week on September 26th (I will update the README accordingly).

> and how will the test set be distributed?

We will release the test conversations in this repository. Submissions will be done via Google form and will close October 3rd.

> and how do i know if I've signed up successfully?

You will not receive a confirmation after submitting the registration form. Anyways, you will be able to submit via the submission form regardless of your registration status, but registration is strongly encouraged so we can better track participants.

**Comment by michael-wzhu** [comment]
Can i ask what time zone are you referring to? And does the deadline (October 3rd) mean the 23:59 pm on October 3rd?

**Comment by Chucy2020** [comment]
> Can i ask what time zone are you referring to? And does the deadline (October 3rd) mean the 23:59 pm on October 3rd


测试集现在没发布，应该是根据美国时间来的

**Comment by jgung** [comment]
We will leave submissions open until October 3rd, Anywhere on Earth (UTC-12). See my comment in the other thread: https://github.com/amazon-research/dstc11-track2-intent-induction/issues/12#issuecomment-1257433111.
