### ISSUE TITLE
About ground-truth label of dialog acts

### ISSUE THREAD

**Issue by RookieZB** [amazon-science/dstc11-track2-intent-induction#11]
In dev set, only predicted labels of dialog acts are provided, so where can I find the ground-truth labels of dialog acts? I think utterances with intent labels include all samples informing intents in dev set, is it correct?

Thanks!

**Comment by jgung** [comment]
Hi @RookieZB, thanks for your question! In short, we will not be providing ground truth dialog act labels for this track.

* For [Task 1 - Intent Clustering](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task1-intent-clustering.md), the turns to be assigned cluster labels will be provided (like the turns in the development data with intent labels).
* For [Task 2 - Open Intent Induction](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task2-open-intent-induction.md), only the dialog act predictions will be provided. There is no guarantee about the overlap between these and the turns provided for Task 1.

I hope this helps. Please let me know if further clarification would be helpful.

**Comment by RookieZB** [comment]
@jgung Thanks for your reply! I understand that ground truth label of dialog act on test set will not be provided. I wonder if ground truth label of dialog act (inform intents) on dev set is available or not? I want to use dev data to train my own classifier detecting sentences containing intents for task2, thus I need labels on dev set.

Thank you.

**Comment by jgung** [comment]
> I wonder if ground truth label of dialog act (inform intents) on dev set is available or not? I want to use dev data to train my own classifier detecting sentences containing intents for task2, thus I need labels on dev set.

We are not releasing ground truth dialog act labels as part of this task, but you are welcome to make use of other publicly available datasets/resources for training a dialog act classifier to improve over the predicted labels.

To clarify, we will be providing dialog act *predictions* with the test data for Task 2 (similar to the predictions provided with the development data).
