### ISSUE TITLE
Will there be a submission site?

### ISSUE THREAD

**Issue by michael-wzhu** [amazon-science/dstc11-track2-intent-induction#12]
Will there be a submission site where you can submit a result and verify whether the format is ok?

**Comment by Jeiyoon** [comment]
Me too. I'm looking for the submission page but I can't find it

**Comment by Chucy2020** [comment]
> Will there be a submission site where you can submit a result and verify whether the format is ok?



> 

The answer submission site may be given after the test set is published

**Comment by jgung** [comment]
@michael-wzhu @Jeiyoon yes, we will share the test conversations and a link to the submission site within the next 24 hours, along with a script to ensure the formatting of entries are okay.

Submissions will then be accepted until Monday October 3rd "anywhere on earth" (UTC-12).

**Comment by Chucy2020** [comment]
> @michael-wzhu @Jeiyoon yes, we will share the test conversations and a link to the submission site within the next 24 hours, along with a script to ensure the formatting of entries are okay.
> 
> Submissions will then be accepted until Monday October 3rd "anywhere on earth" (UTC-12).

ok, thans

**Comment by Jeiyoon** [comment]
@jgung You mean the testset and submission page will be opened soon right?

**Comment by jgung** [comment]
@Jeiyoon @michael-wzhu thanks for your patience! We've just released the test conversations and opened the [submission form](https://forms.gle/m2NWYm22LGGyEYtn9).

See the updated [README.md](https://github.com/amazon-research/dstc11-track2-intent-induction#news) for more details.
