### ISSUE TITLE
A list of intents

### ISSUE THREAD

**Issue by ODDHOOD** [amazon-science/dstc11-track2-intent-induction#13]
You said you will provide a list of intents, where it is, hope you can answer, thank you

**Comment by jgung** [comment]
@ODDHOOD, thanks for your question!

I guess you are referring to the list of turns to be clustered for [Task 1](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task1-intent-clustering.md#task) (please let me know if I'm wrong).

We've indicated these turns in the test conversations using a "DummyLabel" intent:
```json
{
  "turn_id": "banking_0000_001",
  "speaker_role": "Customer",
  "utterance": "Yes I called earlier to see if you could see any pending deposits on my account. I was just wondering if you could check my account balance for me.",
  "dialogue_acts": ["InformIntent"],
  "intents": ["DummyLabel"]
}
```
Any turns in the test set that should be clustered for Task 1 will have an intent label like this. I hope this helps!

**Comment by ODDHOOD** [comment]
> @ODDHOOD, thanks for your question!
> 
> I guess you are referring to the list of turns to be clustered for [Task 1](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task1-intent-clustering.md#task) (please let me know if I'm wrong).
> 
> We've indicated these turns in the test conversations using a "DummyLabel" intent:
> 
> ```json
> {
>   "turn_id": "banking_0000_001",
>   "speaker_role": "Customer",
>   "utterance": "Yes I called earlier to see if you could see any pending deposits on my account. I was just wondering if you could check my account balance for me.",
>   "dialogue_acts": ["InformIntent"],
>   "intents": ["DummyLabel"]
> }
> ```
> 
> Any turns in the test set that should be clustered for Task 1 will have an intent label like this. I hope this helps!

You mean that in a "turn_id" where "dialogue_acts" has the value ["InformIntent"] and "intents" has the value ["DummyLabel"], we need to predict the intent of the sentence, and hopefully I'm right

**Comment by jgung** [comment]
> You mean that in a "turn_id" where "dialogue_acts" has the value ["InformIntent"] and "intents" has the value ["DummyLabel"], we need to predict the intent of the sentence, and hopefully I'm right

* For **Task 1** any turn that is labeled with `"intents": ["DummyLabel"]` should be assigned a cluster label (no matter what the dialogue acts are for that turn). 
* For **[Task 2](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task2-open-intent-induction.md)**, the dialogue act predictions `"InformIntent"` are used. Task 2 _does not use_ these "DummyLabel" turns, but instead must rely on the noisier dialogue act predictions (or other techniques).


If you have doubts, you can run the validation script to check if [your submission](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task1-intent-clustering.md#submissions) has predictions for the correct turns:

```
python3 dstc11/validate_task_inputs.py path_to_your_banking_predictions_file/predictions.json \
--task 1 \
--dialogues dstc11/test-banking/dialogues.jsonl
```

**Comment by ODDHOOD** [comment]
> > You mean that in a "turn_id" where "dialogue_acts" has the value ["InformIntent"] and "intents" has the value ["DummyLabel"], we need to predict the intent of the sentence, and hopefully I'm right
> 
> * For **Task 1** any turn that is labeled with `"intents": ["DummyLabel"]` should be assigned a cluster label (no matter what the dialogues are for that turn).
> * For **[Task 2](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task2-open-intent-induction.md)**, the dialogue act predictions `"InformIntent"` are used. Task 2 _does not use_ these "DummyLabel" turns, but instead must rely on the noisier dialogue act predictions (or other techniques).
> 
> If you have doubts, you can run the validation script to check if [your submission](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task1-intent-clustering.md#submissions) has predictions for the correct turns:
> 
> ```
> python3 dstc11/validate_task_inputs.py path_to_your_banking_predictions_file/predictions.json \
> --task 1 \
> --dialogues dstc11/test-banking/dialogues.jsonl
> ```

I am participating in task 1, I see what you mean, the last question, the submitted prediction file: predictions.json field - "predicted_label": "4" (example), the submitted value should not be 4, but the actual value is right, such as "paybill", I hope you can answer, thank you!

**Comment by jgung** [comment]
>  the last question, the submitted prediction file: predictions.json field - "predicted_label": "4" (example), the submitted value should not be 4, but the actual value is right, such as "paybill", I hope you can answer, thank you!

Thanks for your question!

In the example, a label like "4" is okay to use to indicate the cluster ID. The labels can be any string. The reference labels (like "paybill") will not be released until after the testing phase is over. If you want to generate labels like this, it's okay, but we are not evaluating the naming of intents for this track. Hope that helps.

**Comment by ODDHOOD** [comment]
> > the last question, the submitted prediction file: predictions.json field - "predicted_label": "4" (example), the submitted value should not be 4, but the actual value is right, such as "paybill", I hope you can answer, thank you!
> 
> Thanks for your question!
> 
> In the example, a label like "4" is okay to use to indicate the cluster ID. The labels can be any string. The reference labels (like "paybill") will not be released until after the testing phase is over. If you want to generate labels like this, it's okay, but we are not evaluating the naming of intents for this track. Hope that helps.

thank you so much😀

**Comment by ODDHOOD** [comment]
> > > the last question, the submitted prediction file: predictions.json field - "predicted_label": "4" (example), the submitted value should not be 4, but the actual value is right, such as "paybill", I hope you can answer, thank you!
> 
> Thanks for your question!
> 
> In the example, a label like "4" is okay to use to indicate the cluster ID. The labels can be any string. The reference labels (like "paybill") will not be released until after the testing phase is over. If you want to generate labels like this, it's okay, but we are not evaluating the naming of intents for this track. Hope that helps.

Ask if the final prediction.jsonl file only needs to be -- "turn_id" and "predicted_label" like this:


`{"turn_id": "turn_001_001", "predicted_label": "4"}
{"turn_id": "turn_001_008", "predicted_label": "4"}
{"turn_id": "turn_001_021", "predicted_label": "17"}`

**Comment by jgung** [comment]
That's correct, although just to be sure, each JSON dictionary should be on a single line, like:

```
{"turn_id": "turn_001_001", "predicted_label": "4"}
{"turn_id": "turn_001_008", "predicted_label": "4"}
{"turn_id": "turn_001_021", "predicted_label": "17"}
```

I'd definitely suggest running the [validation script](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/validate_task_inputs.py) to double check there are no errors.

**Comment by ODDHOOD** [comment]
> That's correct, although just to be sure, each JSON dictionary should be on a single line, like:
> 
> ```
> {"turn_id": "turn_001_001", "predicted_label": "4"}
> {"turn_id": "turn_001_008", "predicted_label": "4"}
> {"turn_id": "turn_001_021", "predicted_label": "17"}
> ```
> 
> I'd definitely suggest running the [validation script](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/validate_task_inputs.py) to double check there are no errors.

I get it!Thank you for your patience.
