### ISSUE TITLE
How many submissions from one team are allowed?

### ISSUE THREAD

**Issue by preduct0r** [amazon-science/dstc11-track2-intent-induction#15]

**Comment by jgung** [comment]
Hi @preduct0r, thanks for your question! You are free to update submissions until the deadline, but only _**one submission (system) per task is allowed for each team**_.

If you developed multiple systems as part of the track, or just want to compare across different hyperparameters/random seeds, we encourage you to report your findings in a system paper to submit to the DSTC 11 workshop!
