### ISSUE TITLE
About submission

### ISSUE THREAD

**Issue by ODDHOOD** [amazon-science/dstc11-track2-intent-induction#16]
Is there a requirement for the submitted file name? There is also an option to fill in the email address. Do we have to choose Google Mail? (I don't mean the email address of the bind form)

**Comment by ODDHOOD** [comment]
> Is there a requirement for the submitted file name? There is also an option to fill in the email address. Do we have to choose Google Mail? (I don't mean the email address of the bind form)

![Snipaste_2022-09-30_12-13-22](https://user-images.githubusercontent.com/77596098/193188951-e84b2368-fb3f-4ee7-ad59-3fa5db8905b1.jpg)
That's what I marked above

**Comment by jgung** [comment]
Hi @ODDHOOD, thanks for your questions. The email in this field does not need to be a Google account. This email is used to send the response form once the submission is made (and includes an edit button so you update your response). The Google account sign in is just required for uploading files.

> Is there a requirement for the submitted file name?

No, the file is identified by the form, but I suggest naming them something like `task-2-test-finance.json`.

**Comment by dubingzhu01** [comment]
> This email is used to send the response form once the submission is made

I did not receive the relevant email after submitting the results. Is there something wrong?

**Comment by jgung** [comment]
Hi @dubingzhu01, can you please send an email to dstc11-intent-induction@amazon.com with the email address you used in the form so we can verify that your submission was received?

**Comment by dubingzhu01** [comment]
> so we can verify that your submission was received?

Thank you for your reply . I have sended an email to dstc11-intent-induction@amazon.com. Please help to check it.

**Comment by jgung** [comment]
Hi @dubingzhu01, did you send an email to us in the last 4 hours? I did not see one. Otherwise, you can also try to email dstc11.track2.intent.induction@gmail.com.

I do however believe I received your submission (as of 2022/09/29 9:50:40 AM AST) -- please confirm if this is correct.

**Comment by dubingzhu01** [comment]
> Hi @dubingzhu01, did you send an email to us in the last 4 hours? I did not see one. Otherwise, you can also try to email [dstc11.track2.intent.induction@gmail.com](mailto:dstc11.track2.intent.induction@gmail.com).

* Yes, I resent an email to dstc11.track2.intent.induction@gmail.com and dstc11-intent-induction@amazon.com  with the email address I used in the form (Enterprise email). The status shows it has been successfully sent. Please help to check it. 


> I do however believe I received your submission (as of 2022/09/29 9:50:40 AM AST) -- please confirm if this is correct.
* Yes, that is right. Thank you!

**Comment by jgung** [comment]
Hi, @dubingzhu01 this time I received it, thank you. Yes, we've received your submission.
