### ISSUE TITLE
No google accounts

### ISSUE THREAD

**Issue by michael-wzhu** [amazon-science/dstc11-track2-intent-induction#17]
Hello. It seems the submission is done via google form, but i do not have a google account, and i have difficult creating one. Are there other ways of submitting the files?

**Comment by jgung** [comment]
Hi @michael-wzhu, sorry to hear that you are having difficulties submitting your entry via the form.

If you are unable to use the form, please contact us at dstc11-intent-induction@amazon.com and we will provide you the survey questions/submission instructions separately.

**Comment by jgung** [comment]
Closing for now. Please let me know if you have further questions or concerns (and feel to reach out directly to the above email address).
