### ISSUE TITLE
About the test set samples

### ISSUE THREAD

**Issue by michael-wzhu** [amazon-science/dstc11-track2-intent-induction#18]
I notice that in the test-banking/dialogues.jsonl or test-finance/dialogues.jsonl, there are cases where "dialogue_acts" is "[InformIntent]", but the intents are []. And there are also cases where "dialogue_acts" is "[InformIntent]", but the intents are ["DummyLabel"]. Does this mean we only need to cluster the sentence with the "["DummyLabel"]" intents?

**Comment by michael-wzhu** [comment]
and there are also intents are ['DummyLabel'] and dialogue_acts are [].

**Comment by jgung** [comment]
Hi @michael-wzhu, thanks for your question!

I will copy my response from a previous thread (please let me know if this doesn't answer your question): https://github.com/amazon-research/dstc11-track2-intent-induction/issues/13#issuecomment-1259722704

* For **[Task 1](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task1-intent-clustering.md)** any turn that is labeled with `"intents": ["DummyLabel"]` should be assigned a cluster label (no matter what the dialogue acts are for that turn). 
* For **[Task 2](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task2-open-intent-induction.md)**, the dialogue act predictions `"InformIntent"` are used. Task 2 _does not use_ these "DummyLabel" turns, but instead must rely on the noisier dialogue act predictions (or other techniques).


If you have doubts, you can run the validation script to check if [your submission](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task1-intent-clustering.md#submissions) has predictions for the correct turns:

```
python3 dstc11/validate_task_inputs.py path_to_your_banking_predictions_file/predictions.json \
--task 1 \
--dialogues dstc11/test-banking/dialogues.jsonl
```

**Comment by jgung** [comment]
Closing for now. Please let me know if you have further questions!
