### ISSUE TITLE
Update files in Google Forms

### ISSUE THREAD

**Issue by hwan6615** [amazon-science/dstc11-track2-intent-induction#19]
Hello. I wonder how to update the file that was submitted in Google Forms.

![화면 캡처 2022-10-02 223929](https://user-images.githubusercontent.com/70255720/193457059-7a5989d3-3b66-40c8-a692-241e067cbb45.png)

**Comment by jgung** [comment]
Hi @hwan6615, thanks for bringing this to my attention. 

I've updated the form to accept multiple files. However, only the latest submission will be used for evaluation.

**Comment by hwan6615** [comment]
Thank you!
