### ISSUE TITLE
About running clustering condition on experiments.py

### ISSUE THREAD

**Issue by kwonmha** [amazon-science/dstc11-track2-intent-induction#2]
https://github.com/amazon-research/dstc11-track2-intent-induction/blob/0312cbcd666dc3efb20a32a0658ca5e723081b78/sitod/experiment.py#L133

I think the intention is to skip running clustering when there're prediction results already and also you don't want to ovewrite them.
The codes would be like
skip condition: `Path.exists() and not self._overwrite`
run condition: `not(Path.exists() and not self._ovewrite)` -> `not Path.exists() or self._ovewrite`.

`and not` seems to be changed to `or`.

**Comment by kwonmha** [comment]
It's correctly coded in `OpenIntentInductionExperiment._run_experiment()`

**Comment by jgung** [comment]
@kwonmha thank you very much for bringing this to our attention! The issue has been fixed.
