### ISSUE TITLE
sumission code issue

### ISSUE THREAD

**Issue by luffywalf** [amazon-science/dstc11-track2-intent-induction#20]
i wonder  should we submit our complete code(how we trained model etc) in this deadline("Entry submission deadline: October 3rd, 2022")?  or just summit one schema json file?
thanks!

**Comment by jgung** [comment]
@luffywalf thanks for your question!

You only need to submit the results files specified in [Task 1](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task1-intent-clustering.md#submissions) or [Task 2](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task2-open-intent-induction.md).

Please take the time when you submit your entry to answer the survey questions, which include a short description for each system.

**Comment by luffywalf** [comment]
got it thanks
