### ISSUE TITLE
Why test-utterances.jsonl files have only two sentences?

### ISSUE THREAD

**Issue by Jeiyoon** [amazon-science/dstc11-track2-intent-induction#22]
Hi I've participated dstc11-track2

I did some experiments and found weird scores like:

~~~
RunID	NMI	ARI	ACC	Precision	Recall	F1	Example Coverage	Reference K	K	# Intents	# Utterances	# Utterances per Intent
test_model	100.0	100.0	100.0	100.0	100.0	100.0	100.0	1.0	1.0	42.0	3684.0	87.7
~~~

So I check the test-banking and test-finance dataset, but there are only two sentences:

~~~
{"utterance": "Dummy test utterance 1", "utterance_id": "finance_0000", "intent": "DummyLabel"}
{"utterance": "Dummy test utterance 2", "utterance_id": "finance_0001", "intent": "DummyLabel"}
~~~

Done.

Did i get wrong datasets?

**Comment by jgung** [comment]
Hi @Jeiyoon, thanks for your question. Actually, these test files for DSTC 11 Track 2 Task 2 are just placeholders. We are planning to release the test data for Task 2 later this month, as well as the ground truth cluster labels for Task 1.
