### ISSUE TITLE
Has the final result been announced?

### ISSUE THREAD

**Issue by dubingzhu01** [amazon-science/dstc11-track2-intent-induction#24]
Dstc11 website shows the final result announcement is 10/14, but I didn't find the result entrance. Thank you!

**Comment by Jeiyoon** [comment]
and could you let us know if paper submission starts?

**Comment by dubingzhu01** [comment]
> and could you let us know if paper submission starts?

Hi @Jeiyoon , have you seen the final result?

**Comment by jgung** [comment]
Hi @dubingzhu01, we have not released the results yet. We are planning to release the results on October 24th. Thank you for you patience!

@Jeiyoon Paper submissions information will be announced on the main [DSTC 11 homepage](https://dstc11.dstc.community/).
