### ISSUE TITLE
Where to get my team name?

### ISSUE THREAD

**Issue by dubingzhu01** [amazon-science/dstc11-track2-intent-induction#25]

**Comment by dubingzhu01** [comment]
I have sent an email to you, could you help to confirm it ?

**Comment by jgung** [comment]
Resolved via email, closing.

For others who have submitted, you should receive an email from dstc11.track2.intent.induction@gmail.com with this information. If you submitted an entry and didn't receive an email confirming your submission ID, please email us at this address.
