### ISSUE TITLE
How to evaluate the submissions?

### ISSUE THREAD

**Issue by RookieZB** [amazon-science/dstc11-track2-intent-induction#26]
Hi. It is clarified in the proposal that ACC and NMI will be used to evaluate models for task 1, F1 and coverage will be used to evaluate models for task 2. However, in the released raw results, only ACC is used to rank the submissions. I want to make sure which metrics will be used finally for these two tasks.

Thanks!

**Comment by jgung** [comment]
Hi @RookieZB , thanks for your question. Following the description in [Task 2](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task2-open-intent-induction.md#evaluation) we are also using ACC as the primary metric for ranking submissions in Task 2. I apologize for any discrepancy between the initial proposal and the rules on the task site.
