### ISSUE TITLE
Submission for paper

### ISSUE THREAD

**Issue by dlwlgus53** [amazon-science/dstc11-track2-intent-induction#27]
Hello, when and where do I submit the workshop paper?

**Comment by jgung** [comment]
Hi @dlwlgus53 , thank you for your question. We are awaiting the call for papers from the DSTC 11 organizers – it will be announced on the [DSTC 11 website](https://dstc11.dstc.community/). We will also update the date in this repo when we find out as well.

**Comment by dlwlgus53** [comment]
Thanks!

**Comment by jgung** [comment]
Hi @dlwlgus53, just wanted to mention that the call for papers has been announced here: https://dstc11.dstc.community/calls/call-for-dstc11-workshop-papers
