### ISSUE TITLE
Development dataset: empty utterances

### ISSUE THREAD

**Issue by ValeriaZal** [amazon-science/dstc11-track2-intent-induction#3]
Some utterances in development dataset contain no words. Examples of the utterance content: '', '.', '...'.

The proposal identifies datasets as "spoken conversations with manual transcriptions and annotations".

**The questions are:**
1. What is the reason to use empty transcriptions?
2. Can it affect turns with intents in evaluation datasets?

**Additional info:**
Development dataset contains no turns with Intent or InformIntent labels and empty utterance.
The total number of empty utterances is 142.
The full list of turns with empty utterances: [empty_utterances.txt](https://github.com/amazon-research/dstc11-track2-intent-induction/files/9158142/empty_utterances.txt)

**Comment by jgung** [comment]
Hi @ValeriaZal, thank you for your questions, and bringing attention to these utterances!
> What is the reason to use empty transcriptions?

This appears to be an artifact of the collection/transcription procedure.

> Can it affect turns with intents in evaluation datasets?

These turns can safely be ignored -- in other words, none of these turns will be labeled with intents in the evaluation data.
