### ISSUE TITLE
Development dataset: Agent's turns with intent labels

### ISSUE THREAD

**Issue by ValeriaZal** [amazon-science/dstc11-track2-intent-induction#4]
Some Agent's turns contain intent labels.

The main task of the track is to identify intents of Customer. However, development dataset contains intent labels for Agent's turns as well.

**The questions are:**
1. Should we use only Customer's turns for clustering? Are Agent's turns with intent labels able to affect the results on evaluation datasets?
2. Has Classifier for InformIntent label been trained on all turns with intent labels or only Customer's intents?
3. Has Classifier for InformIntent label been trained on data from all domains (development and evaluation) or only on the particular domain?

**Additional info:**
The total number of Agent's turns with intent labels is 78, including 1 with InformIntent label as well.
The full list of  Agent's turns with intent labels: [agent_intent.txt](https://github.com/amazon-research/dstc11-track2-intent-induction/files/9166919/agent_intent.txt)

**Comment by jgung** [comment]
Hi @ValeriaZal, great questions, thank you again for posting.

> Should we use only Customer's turns for clustering? Are Agent's turns with intent labels able to affect the results on evaluation datasets?

In the evaluation phase for Task 1, we will restrict evaluation to turns where the speaker role is `Customer`. The inputs to this task will **not** contain agent turns. However, there is no restriction against using agent turns to improve at either Task 1 or Task 2 (but we will not explicitly indicate agent turns with intents during the evaluation phase).

> Has Classifier for InformIntent label been trained on all turns with intent labels or only Customer's intents?

The classifier is expected to produce `InformIntent` labels only on customer turns/intents, so `InformIntent` predictions on agent turns can be seen as errors.

> Has Classifier for InformIntent label been trained on data from all domains (development and evaluation) or only on the particular domain?

The classifier used for these predictions is trained on datasets from multiple domains. The automatic `InformIntent` predictions will be similar in quality on the evaluation domains as they are on the development data domain.
