### ISSUE TITLE
About Dialogue act in task 2.

### ISSUE THREAD

**Issue by kwonmha** [amazon-science/dstc11-track2-intent-induction#5]
In `dstc11/task2-open-intent-induction.md`,  it is written as "Participants will be able to use the provided automatic dialog act classifier predictions as inputs to their system.". 
But there seems to be no related codes.
What do we have to do to use that automatic dialogue act classifier?

**Comment by jgung** [comment]
Hi @kwonmha , thank you for your question. We are not releasing the classifier model, but we are releasing its predictions in both the development and evaluation phase of the track. The predictions are included in the `dialogue_acts` field of each turn, e.g. in:
```
{"turn_id": "insurance_000_001", "speaker_role": "Customer", "utterance": "Hi, this is Joe Last and I would like to pay my auto insurance bill.", "dialogue_acts": ["InformIntent"], "intents": ["PayBill"]}
```
the automatic prediction that the turn contains an intent is indicated by `"dialogue_acts": ["InformIntent"]`.

**Comment by kwonmha** [comment]
Thank you for informing.
