### ISSUE TITLE
About task one test set labeling issue

### ISSUE THREAD

**Issue by ODDHOOD** [amazon-science/dstc11-track2-intent-induction#9]
Can the results of the test set be self-created with labels？

**Comment by jgung** [comment]
Hi @ODDHOOD , thanks for your interest in [Task 1](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task1-intent-clustering.md). I'm sorry, but I'm not sure that I understood your question correctly. Could you provide more details or rephrase it please?

**Comment by ODDHOOD** [comment]
Actually, I want to ask the question about the baseline, I reproduced the method, you are using the unsupervised method, where does the label come from? Is it from the test-utterances.jsonl file in the dataset, or from where, and then the baseline method does not use the test-utterances.jsonl file, if it comes from this file, is it not to assign the tags in this file to k clusters (or where the list of intents comes from), and finally, what is the role of this file, thank you for answering my "stupid" question, Hope you understand my question and sincerely appreciate it!


钟2
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amazon-research/dstc11-track2-intent-induction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月16日(星期五) 凌晨4:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amazon-research/dstc11-track2-intent-induction] About task one test set labeling issue (Issue #9)





 
Hi @ODDHOOD , thanks for your interest in Task 1. I'm sorry, but I'm not that I understood your question correctly. Could you provide more details or rephrase it please?

**Comment by jgung** [comment]
Closing this for now, feel free to reach out if you have any additional questions!
